title: Simple File Transfer
description: null
show_downloads: true
github:
  zip_url: https://clearall2.github.io/SimpleFileTransferApp/release/sft.zip
  another_url: https://clearall2.github.io/SimpleFileTransferApp/updater/SFT%20Updater.exe
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
